name: AMI

on:  
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    #types: 
      #- closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set environment variables                
        run: |          
          echo "AWS_DEV_ACCESS_KEY=" ${{ secrets.AWS_DEV_ACCESS_KEY }} > .env
          echo "AWS_DEV_SECRET_KEY=" ${{ secrets.AWS_DEV_SECRET_KEY }} >> .env
          echo "AWS_DEFAULT_REGION=" ${{ secrets.AWS_DEV_REGION }} >> .env
          echo "AWS_SUBNET=subnet-03d40935eb6d4bae2" >> .env
          cat .env

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}

      - name: Run apt update
        run: sudo apt update   
        
      - name: Install node modules
        run: npm i       
      
      - name: Create build artifact
        run: |
          touch project.tar.gz
          tar --exclude=project.tar.gz -czvf project.tar.gz .      
      
      - name: Generate pub file from secrets
        run: |
          echo ${{secrets.EC2_DEMO_PUBLIC_KEY}} > EC2.pub

      - name: Init packer
        run: packer init .

<<<<<<< Updated upstream
=======
      - name: Set environment variables        
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_KEY }}
          export AWS_DEFAULT_REGION="us-east-1"
          
>>>>>>> Stashed changes
      - name: Running the packer script 
        run: packer build ami.pkr.hcl

  