name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build-and-test-node:    
    runs-on: ubuntu-latest    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it            
      - uses: actions/checkout@v3
      
      # Setting up node      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Setup dependencies
        run: npm ci

      - name: Run tests        
        run: npm test 

      - name: Install bats
        run: npm i -g bats
        
      - name: Run bats -v
        run : bats -v
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      
